baseURL = 'https://cordeis.gosoares.com/'
languageCode = 'pt-br'
title = 'Cord√©is do Poeta Manoel Ribeiro'
theme = 'PaperMod'

[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
search = true                                                           # Re-adding this as it was in the plan for search
ShowShareButtons = true
ShowPostNavLinks = true
enableRobotsTXT = true
description = "Acervo de Cord√©is do Poeta Manoel Ribeiro"
keywords = ["cordel", "poesia", "literatura popular", "Manoel Ribeiro"]
author = "Poeta Manoel Ribeiro"

[params.homeInfoParams]
Title = "Ol√°! üëã"
Content = "Bem-vindo ao acervo de Cord√©is do Poeta Manoel Ribeiro."
[[params.socialIcons]]
name = "instagram"
url = "https://instagram.com/poetamanoeldocordelpb"

[[menu.main]]
identifier = "search"
name = "Buscar"
url = "/search/"
weight = 10

[[menu.main]]
identifier = "archives"
name = "Acervo"
url = "/archives/"
weight = 20
